export const ACTION_TYPES = {
    CHANGE_ROWS : 'CHANGE_ROWS',
    CHANGE_COLS : 'CHANGE_COLS',
    DISABLE_CONTROLS : 'DISABLE_CONTROLS',
    ALGORITHM : 'ALGORITHM',
    SPEED : 'SPEED',
    MESSAGE : 'MESSAGE',
    GRID : 'GRID',
    REMOVE_WALLS : 'REMOVE_WALLS',
}